name: flutter_max_way
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0-262.3.beta <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_svg: ^2.0.7
  dio: ^5.3.2
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0
  provider: ^6.0.5
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  freezed: ^2.4.2
  permission_handler: 10.4.3
  yandex_mapkit: 3.3.3
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  hive: 2.2.3
  get_it: 7.6.0
  path_provider: 2.1.0
  firebase_auth: ^4.8.0
  firebase_core: ^2.15.1
  pinput: ^2.2.12


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
     - assets/images/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
